### ISSUE TITLE
Editing gallery while its metadata is being fetched causes exception

### ISSUE THREAD

**Issue by nonamethanks** [Pewpews/happypanda#131]
Trying to edit a gallery while it's fetching metadata returns the red warning to contact the developer, and the following error:

```
Traceback (most recent call last):
  File "/home/nonamethanks/Various/happypanda-alpha/version/gallery.py", line 1242, in replace_edit_gallery
    gallerydb.GalleryDB.begin()
  File "/home/nonamethanks/Various/happypanda-alpha/version/database/db.py", line 374, in begin
    cls.execute(cls, "BEGIN TRANSACTION")
  File "/home/nonamethanks/Various/happypanda-alpha/version/database/db.py", line 400, in execute
    return self._DB_CONN.execute(*args)
sqlite3.OperationalError: cannot start a transaction within a transaction
```

The program keeps working as normal after that as far as I can tell.

**Comment by twiddli** [comment]
Fixed in v0.28.1
