### ISSUE TITLE
Adding two galleries at the same time causes exception

### ISSUE THREAD

**Issue by nonamethanks** [Pewpews/happypanda#136]
Steps to reproduce: 
1) Open the "Add single gallery" window twice
2) Select two galleries
3) Click on "Done" for one of them"
4) Once the first window disappear, click on "Done" for the other
If the first one is still being added in the background, the program will return an exception:

```

Traceback (most recent call last):
  File "/home/nonamethanks/Various/happypanda-master/version/gallery.py", line 617, in addRows
    gallerydb.GalleryDB.add_gallery_return(gallery)
  File "/home/nonamethanks/Various/happypanda-master/version/gallerydb.py", line 520, in add_gallery_return
    ChapterDB.add_chapters(object)
  File "/home/nonamethanks/Various/happypanda-master/version/gallerydb.py", line 643, in add_chapters
    cls.executemany(cls, 'INSERT INTO chapters VALUES(NULL, ?, ?, ?, ?, ?, ?)', executing)
  File "/home/nonamethanks/Various/happypanda-master/version/database/db.py", line 413, in executemany
    return self._DB_CONN.executemany(*args)
sqlite3.IntegrityError: FOREIGN KEY constraint failed

```

Adding to this, the user has no way to tell when a gallery is actually done being added by the program, which eventually causes more problems. The only indicator is the loading wheel, which is not really a good way to tell as its animation sometimes persist several seconds after the task is done, and is already shared by other tasks (like fetching metadata etc).

**Comment by twiddli** [comment]
Fixed in v0.29
