### ISSUE TITLE
Unable to save to db - table series has no artist column

### ISSUE THREAD

**Issue by emmauss** [Pewpews/happypanda#176]
this is an exception thrown after populating the gallery from  directory. this prevents gallery info from being saved. manually adding a 'artist' column to the series table in the db with a sqlite editor fixed it. it is necessary to add the column when the creating a new database, or updating old databases.
exception thrown in cmd:
`Exception in thread Method Queue Thread:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python35\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Emmanuel Hansen\Downloads\Programs\pew\happypanda\version\gallerydb.py", line 92, in process_methods
    r = method(*args)
  File "C:\Users\Emmanuel Hansen\Downloads\Programs\pew\happypanda\version\gallerydb.py", line 463, in add_gallery
    cursor = cls.execute(cls, *default_exec(object))
  File "C:\Users\Emmanuel Hansen\Downloads\Programs\pew\happypanda\version\database\db.py", line 435, in execute
    return self._DB_CONN.execute(*args)
sqlite3.OperationalError: table series has no column named artist`

**Comment by rachmadaniHaryono** [comment]
On which branch /commit are you on @emmauss? 

On alpha branch, database version is not yet updated, which caused old database not converted into new one. 

But I'm not quite sure if new database also broken on initiation. @Pewpews?

**Comment by emmauss** [comment]
alpha branch.

**Comment by twiddli** [comment]
@rachmadaniHaryono DB is broken on initiation.
The DB layout is *completely* wrong. 
It's from a time I tried to rework the DB layout.
This is why tests are good. Haha. 
I'll fix it promptly.

**Comment by twiddli** [comment]
Should be fixed now. Did a test too.
