### ISSUE TITLE
Crash on Arch Linux

### ISSUE THREAD

**Issue by ghost** [Pewpews/happypanda#30]
```
gant@leviathan ~/D/h/version # python main.py                                          14:19:53
Traceback (most recent call last):
  File "main.py", line 226, in <module>
    start()
  File "main.py", line 221, in start
    start_main_window(conn)
  File "main.py", line 153, in start_main_window
    WINDOW = app.AppWindow()
  File "/home/gant/Downloads/happypanda/version/app.py", line 58, in __init__
    self.initUI()
  File "/home/gant/Downloads/happypanda/version/app.py", line 299, in initUI
    self.init_spinners()
  File "/home/gant/Downloads/happypanda/version/app.py", line 482, in init_spinners
    self.data_fetch_spinner = misc.Spinner(self)
  File "/home/gant/Downloads/happypanda/version/misc.py", line 232, in __init__
    self.fade_animation = QPropertyAnimation(self, 'windowOpacity')
TypeError: arguments did not match any overloaded call:
  QPropertyAnimation(QObject parent=None): too many arguments
  QPropertyAnimation(QObject, QByteArray, QObject parent=None): argument 2 has unexpected type 'str'
```

**Comment by twiddli** [comment]
Pushed a fix on master branch. Please redownload/`git pull`.

**Comment by twiddli** [comment]
Resolved
